### ISSUE TITLE
single pin widgets are added at the bottom instead of top and cannot be dragged

### ISSUE THREAD

**Issue by propertunist** [iionly/au_sets#1]
in earlier versions of pinboards, when a single pin widget was added, it would be placed at the top of the first column, near the 'add widgets' button. now though, the widget is added at the bottom of the page and then cannot be dragged. i need to refresh the page before i can move the new widgets.

**Comment by iionly** [comment]
I think I'm either not understanding the problem or I can't reproduce it. If I add a new widget to a pinboard (single pin widget or another one), it gets added at the top of column 1 and I can drag and drop it elsewhere immediately. Could it be that another 3rd party plugin causes the problem for you?

**Comment by propertunist** [comment]
i don't think i have any plugins that might be effecting this. i just tested with my theme disabled and the problem remained. i have a pinboard here with 4 columns in it and the new widget is always added to column 4. i also just tested with a single column pinboard and the widget goes to column 1 and cannot be moved.
there is nothing relevant in the console log. i can edit the widgets as normal, just not drag them anywhere.

**Comment by iionly** [comment]
Sorry. But I simply can't reproduce this. I can drag and drop widgets perfectly alright.

You are trying to drag the widgets by clicking on the title section of the widgets, aren't you? This is the only part of the widget that allows you to grab it and move it (but this is basically the same as for widgets on other pages like profile pages etc.).

Did you delete the old plugin folder before upgrading? This is the only thing that I can think of that might cause the problem for you if there are orphaned files from an older version still there that cause a conflict now.

**Comment by propertunist** [comment]
i just tested that idea by deleting the folder and re-downloading the package from github. the outcome though is the same. the only other thought i have is that page refreshes are triggered when widgets are deleted on the page, but i'm not sure if that is by design or not.

i have been using au_sets for years on 1.8.x so am familiar with how the dragging and dropping is intended to function.

**Comment by iionly** [comment]
I think I might have not correctly understood what you said before. You said "widget is added at end of page" while I understood "widget is added at the bottom of the column".

What you are describing is exactly what failed to work with the older AU_Sets version of Elgg 1.8 when used on Elgg 1.9 or newer. This should really be fixed in the updated version here. And again: it works for me with no issues. Are you sure you dowloaded the correct branch from github, i.e. master branch from my repo and not any other branch from any other repo?

**Comment by propertunist** [comment]
oh ok - i recall there were several problems across versions - yes.
yes, i downloaded the master branch from your repo here and that is all i am using.

**Comment by iionly** [comment]
Then returning to the idea of another 3rd party plugin causing the problem (this could include any plugin suggested by the AU_Sets plugin itself and also the suggested other AU plugins).

**Comment by propertunist** [comment]
i only have dependencies 'widget manager' and 'liked content' installed here and liked content doesn't do anything at all with widgets, so i would be surprised if liked content is involved.
i just disabled liked content to test that possibility and the problem persists with liked content disabled.

**Comment by iionly** [comment]
Widget Manager shouldn't be a problem. That's a plugin I have installed too (version 5.0 on Elgg 1.9). Sorry. But I have no idea why it fails to work for you.
